services:
  - type: web
    name: sahayakcircle
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11
